[[0]]
key = "date"
px = 0.0
py = 0.0

[[0]]
key = "weather"
px = 0.0974
py = 0.0

[[0]]
key = "calendar"
px = 0.19271
py = 0.0

[[0]]
key = "cpu_info"
px = 0.81042
py = 0.82732

[[0]]
key = "ram_info"
px = 0.90521
py = 0.82732
