DEFAULT = {
    "general": {
        "debug": False,
        "wallpapers_dir": "src/assets/wallpaper_example/",
        "keyboard_layouts": ["us"],
        "weather_location": "",
    },
    "dock": {
        "enabled": True,
        "auto_hide": True,
        "always_occluded": False,
        "icon_size": 52,
        "hide_special_workspace_apps": True,
    },
    "panel": {
        "imac_button": True,
        "systray": True,
        "systray_ignore": ["blueman", "network"],
        "control_center": True,
        "search": True,
        "global_menu": True,
        "network": True,
        "battery": True,
        "notification_center": True,
        "workspace_indicator": True,
        "bluetooth": True,
        "date_time": True,
        "night_light_temperature": 4500,
        "notch": True,
        "osd": True,
        "hide_special_workspace": True,
        "custom_mods": True,
    },
    "switcher": {
        "live_preview": True,
        "live_preview_delay_ms": 200,
        "window_switcher": True,
    },
    "notification": {
        "timeout": "5s",
        "ignored_apps": ["Hyprshot"],
        "limited_apps_history": ["Spotify"],
    },
}
