DEFAULT = {
    "wallpapers_dir": "~/Pictures/Wallpapers/",
    "dock_enabled": True,
    "dock_auto_hide": True,
    "dock_always_occluded": False,
    "dock_icon_size": 52,
    "window_switcher_items_per_row": 10,
    "hide_special_workspace": True,
    "dock_hide_special_workspace_apps": True,
    "notification_timeout": "5s",
    "notification_ignored_apps": ["Hyprshot"],
    "notification_limited_apps_history": ["Spotify"],
    "imac_button": True,
    "systray": True,
    "control_center": True,
    "search": True,
    "global_menu": True,
    "network": True,
    "battery": True,
    "notification_center": True,
    "workspace_indicator": True,
    "bluetooth": True,
    "date_time": True,
    "keyboard_layouts": ["us", "np"],
    "window_switcher": True,
    "osd": True,
    "systray_ignore": ["blueman", "network"],
}
