from config.data import (
    APP_NAME,
    APP_NAME_CAP,
    NOTIF_POS_DEFAULT,
    NOTIF_POS_KEY,
    WALLPAPERS_DIR_DEFAULT,
)

SOURCE_STRING = f"""
# {APP_NAME_CAP}
source = ~/{APP_NAME_CAP}/config/hypr/{APP_NAME}.conf
"""

DEFAULTS = {
    "prefix_restart": "SUPER ALT",
    "suffix_restart": "B",
    "prefix_axmsg": "SUPER",
    "suffix_axmsg": "A",
    "prefix_application_switcher": "ALT",
    "suffix_application_switcher": "TAB",
    "prefix_dash": "SUPER",
    "suffix_dash": "D",
    "prefix_bluetooth": "SUPER SHIFT",
    "suffix_bluetooth": "B",
    "prefix_pins": "SUPER",
    "suffix_pins": "Q",
    "prefix_kanban": "SUPER",
    "suffix_kanban": "N",
    "prefix_launcher": "SUPER",
    "suffix_launcher": "R",
    "prefix_tmux": "SUPER",
    "suffix_tmux": "T",
    "prefix_cliphist": "SUPER",
    "suffix_cliphist": "V",
    "prefix_toolbox": "SUPER",
    "suffix_toolbox": "S",
    "prefix_overview": "SUPER",
    "suffix_overview": "TAB",
    "prefix_wallpapers": "SUPER",
    "suffix_wallpapers": "COMMA",
    "prefix_randwall": "SUPER SHIFT",
    "suffix_randwall": "COMMA",
    "prefix_emoji": "SUPER",
    "suffix_emoji": "PERIOD",
    "prefix_power": "SUPER",
    "suffix_power": "ESCAPE",
    "prefix_caffeine": "SUPER SHIFT",
    "suffix_caffeine": "M",
    "prefix_css": "SUPER SHIFT",
    "suffix_css": "B",
    "prefix_restart_inspector": "SUPER CTRL ALT",
    "suffix_restart_inspector": "B",
    "wallpapers_dir": "/home/sankalp/Pictures/wallpapers",
    "vertical": True,
    "dock_enabled": True,
    "dock_always_occluded": False,
    "dock_auto_hide": True,
    "terminal_command": "kitty -e",
    "corners_visible": False,
    "dock_theme": "Pills",
    "notif_pos": "Top",
    "dock_position": "Bottom",
    "dock_icon_size": 20,
    "dock_workspaces_visible": True,
    "dock_metrics_visible": True,
    "dock_battery_visible": True,
    "dock_date_time_visible": True,
    "dock_controls_visible": True,
    "dock_indicators_visible": True,
    "dock_applications_visible": True,
    "dock_language_visible": True,
    "workspace_nums": False,
    "workspace_use_chinese_numerals": False,
    "workspace_dots": False,
    "dock_music_player": True,
    "window_switcher_items_per_row": 13,
    "metrics_visible": {
        "cpu": True,
        "ram": True,
        "disk": True,
        "swap": True,
        "gpu": False,
    },
    "metrics_disks": ["/"],
}
